-- Enforce canonical role/action policy before existing scoped business logic.
-- Existing implementations are renamed and retained; wrappers preserve signatures and defaults.

INSERT INTO platform_identity.action_catalog(object_type,action,display_name,data_class,consequence,data_action)
VALUES('capacity','request','Request project capacity','delivery','normal','write')
ON CONFLICT (object_type,action) DO UPDATE SET display_name=EXCLUDED.display_name,data_class=EXCLUDED.data_class,consequence=EXCLUDED.consequence,data_action=EXCLUDED.data_action,active=1;
INSERT INTO platform_identity.role_action_policy(role_key,object_type,action,authority_mode,notes)
SELECT r.role_key,'capacity','request','deny','Default deny; explicitly overridden below.' FROM platform_identity.role_catalog r WHERE r.active=1
ON CONFLICT (role_key,object_type,action) DO NOTHING;
UPDATE platform_identity.role_action_policy SET authority_mode='allow',condition_code=NULL,notes='Project management may request capacity; allocation remains Resource Manager authority.'
WHERE role_key IN ('project-manager','project-director') AND object_type='capacity' AND action='request';

CREATE OR REPLACE FUNCTION goliath_api.require_capability(p_assignment_id text,p_object_type text,p_action text)
RETURNS text
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path TO 'public','platform_identity','auth','goliath_api'
AS $function$
DECLARE v_mode text;
BEGIN
  v_mode:=goliath_api.capability_mode(p_assignment_id,p_object_type,p_action);
  IF v_mode='deny' THEN
    RAISE EXCEPTION 'This responsibility is not authorised for %.%.',p_object_type,p_action USING ERRCODE='42501';
  END IF;
  RETURN v_mode;
END
$function$;
REVOKE ALL ON FUNCTION goliath_api.require_capability(text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;

-- Rename current tested implementations once.
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_confirm_commitment_candidate(text,text,text,text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.confirm_commitment_candidate(text,text,text,text,text,text,text,text) RENAME TO _policy_confirm_commitment_candidate; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_activate_commitment(text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.activate_commitment(text,text,text) RENAME TO _policy_activate_commitment; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_create_decision(text,text,text,text,text,text,integer,jsonb,text,text,jsonb)') IS NULL THEN ALTER FUNCTION goliath_api.create_decision(text,text,text,text,text,text,integer,jsonb,text,text,jsonb) RENAME TO _policy_create_decision; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_resolve_decision(text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.resolve_decision(text,text,text,text,text) RENAME TO _policy_resolve_decision; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_create_commitment_dependency(text,text,text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.create_commitment_dependency(text,text,text,text,text,text,text) RENAME TO _policy_create_commitment_dependency; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_acknowledge_commitment_dependency(text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.acknowledge_commitment_dependency(text,text,text,text,text) RENAME TO _policy_acknowledge_commitment_dependency; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_create_requirement(text,text,text,text,text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.create_requirement(text,text,text,text,text,text,text,text,text) RENAME TO _policy_create_requirement; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_create_raid_item(text,text,text,text,text,text,integer,integer,text,text,text,text,jsonb)') IS NULL THEN ALTER FUNCTION goliath_api.create_raid_item(text,text,text,text,text,text,integer,integer,text,text,text,text,jsonb) RENAME TO _policy_create_raid_item; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_submit_initial_baseline(text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.submit_initial_baseline(text,text,text,text) RENAME TO _policy_submit_initial_baseline; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_finalize_initial_baseline(text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.finalize_initial_baseline(text,text,text) RENAME TO _policy_finalize_initial_baseline; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_project_report_preview(text,text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.project_report_preview(text,text,text,text,text,text) RENAME TO _policy_project_report_preview; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_snapshot_project_report(text,text,text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.snapshot_project_report(text,text,text,text,text,text,text) RENAME TO _policy_snapshot_project_report; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_create_resource_demand(text,text,text,text,text,text,text,real)') IS NULL THEN ALTER FUNCTION goliath_api.create_resource_demand(text,text,text,text,text,text,text,real) RENAME TO _policy_create_resource_demand; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_resource_capacity_desk(text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.resource_capacity_desk(text,text,text) RENAME TO _policy_resource_capacity_desk; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_allocate_resource(text,text,text,real,text)') IS NULL THEN ALTER FUNCTION goliath_api.allocate_resource(text,text,text,real,text) RENAME TO _policy_allocate_resource; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_admin_create_identity_invitation(text,text,text,integer)') IS NULL THEN ALTER FUNCTION goliath_api.admin_create_identity_invitation(text,text,text,integer) RENAME TO _policy_admin_create_identity_invitation; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_admin_grant_responsibility(text,text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.admin_grant_responsibility(text,text,text,text,text,text) RENAME TO _policy_admin_grant_responsibility; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_admin_revoke_responsibility(text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.admin_revoke_responsibility(text,text,text) RENAME TO _policy_admin_revoke_responsibility; END IF; END $$;

REVOKE ALL ON FUNCTION goliath_api._policy_confirm_commitment_candidate(text,text,text,text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_activate_commitment(text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_create_decision(text,text,text,text,text,text,integer,jsonb,text,text,jsonb) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_resolve_decision(text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_create_commitment_dependency(text,text,text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_acknowledge_commitment_dependency(text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_create_requirement(text,text,text,text,text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_create_raid_item(text,text,text,text,text,text,integer,integer,text,text,text,text,jsonb) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_submit_initial_baseline(text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_finalize_initial_baseline(text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_project_report_preview(text,text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_snapshot_project_report(text,text,text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_create_resource_demand(text,text,text,text,text,text,text,real) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_resource_capacity_desk(text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_allocate_resource(text,text,text,real,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_admin_create_identity_invitation(text,text,text,integer) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_admin_grant_responsibility(text,text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_admin_revoke_responsibility(text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;

CREATE OR REPLACE FUNCTION goliath_api.confirm_commitment_candidate(p_assignment_id text,p_candidate_id text,p_workstream_id text,p_type text,p_owner_id text,p_committed_date text,p_committed_date_kind text,p_acceptance_criteria text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'commitment','confirm-candidate'); RETURN goliath_api._policy_confirm_commitment_candidate(p_assignment_id,p_candidate_id,p_workstream_id,p_type,p_owner_id,p_committed_date,p_committed_date_kind,p_acceptance_criteria); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.activate_commitment(p_assignment_id text,p_commitment_id text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'commitment','activate'); RETURN goliath_api._policy_activate_commitment(p_assignment_id,p_commitment_id,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.create_decision(p_assignment_id text,p_project_id text,p_question text,p_decision_owner_id text,p_needed_by text,p_impact_if_late text,p_impact_weight integer DEFAULT 1,p_options jsonb DEFAULT '[]'::jsonb,p_recommendation text DEFAULT NULL,p_recommendation_origin text DEFAULT 'human',p_commitment_ids jsonb DEFAULT '[]'::jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'decision','create'); RETURN goliath_api._policy_create_decision(p_assignment_id,p_project_id,p_question,p_decision_owner_id,p_needed_by,p_impact_if_late,p_impact_weight,p_options,p_recommendation,p_recommendation_origin,p_commitment_ids); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.resolve_decision(p_assignment_id text,p_decision_id text,p_state text,p_choice text,p_reason text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'decision','resolve'); RETURN goliath_api._policy_resolve_decision(p_assignment_id,p_decision_id,p_state,p_choice,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.create_commitment_dependency(p_assignment_id text,p_consumer_commitment_id text,p_provider_type text,p_provider_ref text,p_needed_by text,p_acceptance_criteria text,p_provider_commitment_id text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'dependency','create'); RETURN goliath_api._policy_create_commitment_dependency(p_assignment_id,p_consumer_commitment_id,p_provider_type,p_provider_ref,p_needed_by,p_acceptance_criteria,p_provider_commitment_id); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.acknowledge_commitment_dependency(p_assignment_id text,p_dependency_id text,p_side text,p_promised_date text DEFAULT NULL,p_reason text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'dependency','acknowledge'); RETURN goliath_api._policy_acknowledge_commitment_dependency(p_assignment_id,p_dependency_id,p_side,p_promised_date,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.create_requirement(p_assignment_id text,p_project_id text,p_title text,p_master_system text,p_source_ref text,p_source_version text,p_verbatim_text text,p_owner_id text,p_priority text DEFAULT 'medium') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'requirement','create'); RETURN goliath_api._policy_create_requirement(p_assignment_id,p_project_id,p_title,p_master_system,p_source_ref,p_source_version,p_verbatim_text,p_owner_id,p_priority); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.create_raid_item(p_assignment_id text,p_project_id text,p_item_type text,p_title text,p_description text,p_owner_id text,p_likelihood_rating integer DEFAULT NULL,p_impact_rating integer DEFAULT NULL,p_response text DEFAULT NULL,p_trigger_type text DEFAULT NULL,p_trigger_ref text DEFAULT NULL,p_validation_date text DEFAULT NULL,p_commitment_ids jsonb DEFAULT '[]'::jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ DECLARE v_action text; BEGIN v_action:=CASE p_item_type WHEN 'risk' THEN 'create-risk' WHEN 'issue' THEN 'create-issue' WHEN 'assumption' THEN 'create-assumption' ELSE NULL END; IF v_action IS NULL THEN RAISE EXCEPTION 'RAID type must be risk, issue or assumption.' USING ERRCODE='22023'; END IF; PERFORM goliath_api.require_capability(p_assignment_id,'raid',v_action); RETURN goliath_api._policy_create_raid_item(p_assignment_id,p_project_id,p_item_type,p_title,p_description,p_owner_id,p_likelihood_rating,p_impact_rating,p_response,p_trigger_type,p_trigger_ref,p_validation_date,p_commitment_ids); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.submit_initial_baseline(p_assignment_id text,p_project_id text,p_approver_user_id text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'baseline','submit'); RETURN goliath_api._policy_submit_initial_baseline(p_assignment_id,p_project_id,p_approver_user_id,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.finalize_initial_baseline(p_assignment_id text,p_project_id text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'baseline','finalize'); RETURN goliath_api._policy_finalize_initial_baseline(p_assignment_id,p_project_id,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.project_report_preview(p_assignment_id text,p_project_id text,p_audience text,p_period_kind text DEFAULT 'current',p_period_start text DEFAULT NULL,p_period_end text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'report','read'); RETURN goliath_api._policy_project_report_preview(p_assignment_id,p_project_id,p_audience,p_period_kind,p_period_start,p_period_end); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.snapshot_project_report(p_assignment_id text,p_project_id text,p_audience text,p_period_kind text DEFAULT 'weekly',p_period_start text DEFAULT NULL,p_period_end text DEFAULT NULL,p_external_approval_reason text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'report','snapshot'); RETURN goliath_api._policy_snapshot_project_report(p_assignment_id,p_project_id,p_audience,p_period_kind,p_period_start,p_period_end,p_external_approval_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.create_resource_demand(p_assignment_id text,p_project_id text,p_team_id text,p_org_unit_id text,p_skill text,p_period_start text,p_period_end text,p_required_hours real) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'capacity','request'); RETURN goliath_api._policy_create_resource_demand(p_assignment_id,p_project_id,p_team_id,p_org_unit_id,p_skill,p_period_start,p_period_end,p_required_hours); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.resource_capacity_desk(p_assignment_id text,p_period_start text,p_period_end text) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'capacity','read'); RETURN goliath_api._policy_resource_capacity_desk(p_assignment_id,p_period_start,p_period_end); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.allocate_resource(p_assignment_id text,p_demand_id text,p_resource_id text,p_hours real,p_reason text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'capacity','allocate'); RETURN goliath_api._policy_allocate_resource(p_assignment_id,p_demand_id,p_resource_id,p_hours,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.admin_create_identity_invitation(p_acting_assignment_id text,p_email text,p_user_id text,p_expires_hours integer DEFAULT 168) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','neon_auth','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_acting_assignment_id,'identity','invite'); RETURN goliath_api._policy_admin_create_identity_invitation(p_acting_assignment_id,p_email,p_user_id,p_expires_hours); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.admin_grant_responsibility(p_acting_assignment_id text,p_user_id text,p_role text,p_scope_type text,p_scope_id text,p_team_id text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_acting_assignment_id,'responsibility','grant'); RETURN goliath_api._policy_admin_grant_responsibility(p_acting_assignment_id,p_user_id,p_role,p_scope_type,p_scope_id,p_team_id); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.admin_revoke_responsibility(p_acting_assignment_id text,p_target_assignment_id text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_acting_assignment_id,'responsibility','revoke'); RETURN goliath_api._policy_admin_revoke_responsibility(p_acting_assignment_id,p_target_assignment_id,p_reason); END $function$;

GRANT EXECUTE ON FUNCTION goliath_api.confirm_commitment_candidate(text,text,text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.activate_commitment(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.create_decision(text,text,text,text,text,text,integer,jsonb,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.resolve_decision(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.create_commitment_dependency(text,text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.acknowledge_commitment_dependency(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.create_requirement(text,text,text,text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.create_raid_item(text,text,text,text,text,text,integer,integer,text,text,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.submit_initial_baseline(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.finalize_initial_baseline(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.project_report_preview(text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.snapshot_project_report(text,text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.create_resource_demand(text,text,text,text,text,text,text,real) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.resource_capacity_desk(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.allocate_resource(text,text,text,real,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.admin_create_identity_invitation(text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.admin_grant_responsibility(text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.admin_revoke_responsibility(text,text,text) TO authenticated;
