-- Complete centralized capability enforcement for remaining material authenticated write RPCs.
-- Existing object/scope/ownership checks remain authoritative underneath the capability gate.

-- Existing wrapper-backed lifecycle functions can be replaced directly.
CREATE OR REPLACE FUNCTION goliath_api.baseline_requirement(p_assignment_id text,p_requirement_id text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api'
AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'requirement','baseline'); RETURN goliath_api._baseline_requirement_internal(p_assignment_id,p_requirement_id,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.accept_requirement(p_assignment_id text,p_requirement_id text,p_evidence_refs jsonb,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api'
AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'requirement','accept'); RETURN goliath_api._accept_requirement_internal(p_assignment_id,p_requirement_id,p_evidence_refs,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.evaluate_raid_triggers(p_assignment_id text,p_project_id text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api'
AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'raid','evaluate-triggers'); RETURN goliath_api._evaluate_raid_triggers_internal(p_assignment_id,p_project_id); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.convert_raid_trigger_to_issue(p_assignment_id text,p_trigger_event_id text,p_owner_id text,p_description text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api'
AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'raid','convert-trigger'); RETURN goliath_api._convert_raid_trigger_to_issue_internal(p_assignment_id,p_trigger_event_id,p_owner_id,p_description,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.finalize_change_request(p_assignment_id text,p_change_request_id text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api'
AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'change','finalize'); RETURN goliath_api._finalize_change_request_internal(p_assignment_id,p_change_request_id,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.respond_notification(p_assignment_id text,p_notification_id text,p_action text,p_reason text DEFAULT NULL,p_snooze_until text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api'
AS $function$ DECLARE v_class text; BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'notification','respond'); SELECT data_class INTO v_class FROM public.pc_notifications WHERE id=p_notification_id; IF v_class IS NULL OR NOT goliath_api.context_has_data_class(p_assignment_id,v_class,'read') THEN RAISE EXCEPTION 'Notification data class is not available to this responsibility.' USING ERRCODE='42501'; END IF; RETURN goliath_api._respond_notification_internal(p_assignment_id,p_notification_id,p_action,p_reason,p_snooze_until); END $function$;

-- Rename tested direct implementations and expose policy wrappers.
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_link_requirement(text,text,text,text,text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.link_requirement(text,text,text,text,text,text,text,text,text) RENAME TO _policy_link_requirement; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_confirm_requirement_link(text,text,boolean,text)') IS NULL THEN ALTER FUNCTION goliath_api.confirm_requirement_link(text,text,boolean,text) RENAME TO _policy_confirm_requirement_link; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_create_change_request(text,text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.create_change_request(text,text,text,text,text,text) RENAME TO _policy_create_change_request; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_prepare_change_request(text,text,text,text,integer,text,real,text,text,text,text,text,jsonb)') IS NULL THEN ALTER FUNCTION goliath_api.prepare_change_request(text,text,text,text,integer,text,real,text,text,text,text,text,jsonb) RENAME TO _policy_prepare_change_request; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_create_handoff(text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.create_handoff(text,text,text,text,text) RENAME TO _policy_create_handoff; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_respond_handoff(text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.respond_handoff(text,text,text,text) RENAME TO _policy_respond_handoff; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_update_activity(text,text,text,text,text,text,real,text,boolean,jsonb,integer)') IS NULL THEN ALTER FUNCTION goliath_api.update_activity(text,text,text,text,text,text,real,text,boolean,jsonb,integer) RENAME TO _policy_update_activity; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_assign_activity(text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.assign_activity(text,text,text,text) RENAME TO _policy_assign_activity; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_set_commitment_evidence_spec(text,text,jsonb,text)') IS NULL THEN ALTER FUNCTION goliath_api.set_commitment_evidence_spec(text,text,jsonb,text) RENAME TO _policy_set_commitment_evidence_spec; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_set_workstream_methodology(text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.set_workstream_methodology(text,text,text,text) RENAME TO _policy_set_workstream_methodology; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_record_pm_assessment(text,text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.record_pm_assessment(text,text,text,text,text) RENAME TO _policy_record_pm_assessment; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_record_commitment_health(text,text)') IS NULL THEN ALTER FUNCTION goliath_api.record_commitment_health(text,text) RENAME TO _policy_record_commitment_health; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_update_raid_item(text,text,text,text,integer,integer,text)') IS NULL THEN ALTER FUNCTION goliath_api.update_raid_item(text,text,text,text,integer,integer,text) RENAME TO _policy_update_raid_item; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_delegate_decision(text,text,text,text)') IS NULL THEN ALTER FUNCTION goliath_api.delegate_decision(text,text,text,text) RENAME TO _policy_delegate_decision; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_refresh_responsibility_notifications(text,text)') IS NULL THEN ALTER FUNCTION goliath_api.refresh_responsibility_notifications(text,text) RENAME TO _policy_refresh_responsibility_notifications; END IF; END $$;
DO $$ BEGIN IF to_regprocedure('goliath_api._policy_admin_set_data_class_override(text,text,text,boolean,boolean,text)') IS NULL THEN ALTER FUNCTION goliath_api.admin_set_data_class_override(text,text,text,boolean,boolean,text) RENAME TO _policy_admin_set_data_class_override; END IF; END $$;

REVOKE ALL ON FUNCTION goliath_api._policy_link_requirement(text,text,text,text,text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_confirm_requirement_link(text,text,boolean,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_create_change_request(text,text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_prepare_change_request(text,text,text,text,integer,text,real,text,text,text,text,text,jsonb) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_create_handoff(text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_respond_handoff(text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_update_activity(text,text,text,text,text,text,real,text,boolean,jsonb,integer) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_assign_activity(text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_set_commitment_evidence_spec(text,text,jsonb,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_set_workstream_methodology(text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_record_pm_assessment(text,text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_record_commitment_health(text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_update_raid_item(text,text,text,text,integer,integer,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_delegate_decision(text,text,text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_refresh_responsibility_notifications(text,text) FROM PUBLIC, authenticated, goliath_web_anon;
REVOKE ALL ON FUNCTION goliath_api._policy_admin_set_data_class_override(text,text,text,boolean,boolean,text) FROM PUBLIC, authenticated, goliath_web_anon;

CREATE OR REPLACE FUNCTION goliath_api.link_requirement(p_assignment_id text,p_requirement_id text,p_link_type text,p_target_system text,p_target_type text,p_target_id text,p_target_version text DEFAULT NULL,p_origin text DEFAULT 'human',p_confidence text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'requirement','link'); RETURN goliath_api._policy_link_requirement(p_assignment_id,p_requirement_id,p_link_type,p_target_system,p_target_type,p_target_id,p_target_version,p_origin,p_confidence); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.confirm_requirement_link(p_assignment_id text,p_link_id text,p_accept boolean,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'requirement','confirm-link'); RETURN goliath_api._policy_confirm_requirement_link(p_assignment_id,p_link_id,p_accept,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.create_change_request(p_assignment_id text,p_project_id text,p_source_type text,p_source_ref text,p_title text,p_description text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'change','create'); RETURN goliath_api._policy_create_change_request(p_assignment_id,p_project_id,p_source_type,p_source_ref,p_title,p_description); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.prepare_change_request(p_assignment_id text,p_change_request_id text,p_classification text,p_scope_impact text,p_schedule_impact_days integer,p_capacity_impact text,p_cost_impact_amount real,p_cost_impact_currency text,p_risk_impact text,p_dependency_impact text,p_impact_completeness text,p_approver_user_id text,p_commitment_changes jsonb DEFAULT '[]'::jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'change','prepare'); RETURN goliath_api._policy_prepare_change_request(p_assignment_id,p_change_request_id,p_classification,p_scope_impact,p_schedule_impact_days,p_capacity_impact,p_cost_impact_amount,p_cost_impact_currency,p_risk_impact,p_dependency_impact,p_impact_completeness,p_approver_user_id,p_commitment_changes); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.create_handoff(p_assignment_id text,p_source_activity_id text,p_target_activity_id text,p_receiver_id text,p_deliverable_version text DEFAULT '1') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'handoff','create'); RETURN goliath_api._policy_create_handoff(p_assignment_id,p_source_activity_id,p_target_activity_id,p_receiver_id,p_deliverable_version); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.respond_handoff(p_assignment_id text,p_handoff_id text,p_state text,p_reason text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'handoff','respond'); RETURN goliath_api._policy_respond_handoff(p_assignment_id,p_handoff_id,p_state,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.update_activity(p_assignment_id text,p_activity_id text,p_status text DEFAULT NULL,p_forecast_finish text DEFAULT NULL,p_actual_start text DEFAULT NULL,p_actual_finish text DEFAULT NULL,p_percent_complete real DEFAULT NULL,p_blocker text DEFAULT NULL,p_clear_blocker boolean DEFAULT false,p_evidence_refs jsonb DEFAULT '[]'::jsonb,p_expected_revision integer DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'work','update'); RETURN goliath_api._policy_update_activity(p_assignment_id,p_activity_id,p_status,p_forecast_finish,p_actual_start,p_actual_finish,p_percent_complete,p_blocker,p_clear_blocker,p_evidence_refs,p_expected_revision); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.assign_activity(p_assignment_id text,p_activity_id text,p_assignee_id text,p_reason text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'work','assign'); RETURN goliath_api._policy_assign_activity(p_assignment_id,p_activity_id,p_assignee_id,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.set_commitment_evidence_spec(p_assignment_id text,p_commitment_id text,p_evidence_spec jsonb,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'commitment','set-evidence-spec'); RETURN goliath_api._policy_set_commitment_evidence_spec(p_assignment_id,p_commitment_id,p_evidence_spec,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.set_workstream_methodology(p_assignment_id text,p_workstream_id text,p_methodology text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'workstream','set-methodology'); RETURN goliath_api._policy_set_workstream_methodology(p_assignment_id,p_workstream_id,p_methodology,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.record_pm_assessment(p_assignment_id text,p_project_id text,p_commitment_id text,p_state text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'health','pm-assessment'); RETURN goliath_api._policy_record_pm_assessment(p_assignment_id,p_project_id,p_commitment_id,p_state,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.record_commitment_health(p_assignment_id text,p_commitment_id text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'health','record-snapshot'); RETURN goliath_api._policy_record_commitment_health(p_assignment_id,p_commitment_id); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.update_raid_item(p_assignment_id text,p_raid_id text,p_state text,p_response text,p_likelihood_rating integer DEFAULT NULL,p_impact_rating integer DEFAULT NULL,p_reason text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'raid','update'); RETURN goliath_api._policy_update_raid_item(p_assignment_id,p_raid_id,p_state,p_response,p_likelihood_rating,p_impact_rating,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.delegate_decision(p_assignment_id text,p_decision_id text,p_delegate_user_id text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'decision','delegate'); RETURN goliath_api._policy_delegate_decision(p_assignment_id,p_decision_id,p_delegate_user_id,p_reason); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.refresh_responsibility_notifications(p_assignment_id text,p_project_id text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_assignment_id,'notification','refresh'); RETURN goliath_api._policy_refresh_responsibility_notifications(p_assignment_id,p_project_id); END $function$;
CREATE OR REPLACE FUNCTION goliath_api.admin_set_data_class_override(p_acting_assignment_id text,p_target_assignment_id text,p_data_class text,p_can_read boolean,p_can_write boolean,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','platform_identity','auth','goliath_api' AS $function$ BEGIN PERFORM goliath_api.require_capability(p_acting_assignment_id,'access','data-class-override'); RETURN goliath_api._policy_admin_set_data_class_override(p_acting_assignment_id,p_target_assignment_id,p_data_class,p_can_read,p_can_write,p_reason); END $function$;

GRANT EXECUTE ON FUNCTION goliath_api.baseline_requirement(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.accept_requirement(text,text,jsonb,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.evaluate_raid_triggers(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.convert_raid_trigger_to_issue(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.finalize_change_request(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.respond_notification(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.link_requirement(text,text,text,text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.confirm_requirement_link(text,text,boolean,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.create_change_request(text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.prepare_change_request(text,text,text,text,integer,text,real,text,text,text,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.create_handoff(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.respond_handoff(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.update_activity(text,text,text,text,text,text,real,text,boolean,jsonb,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.assign_activity(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.set_commitment_evidence_spec(text,text,jsonb,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.set_workstream_methodology(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.record_pm_assessment(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.record_commitment_health(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.update_raid_item(text,text,text,text,integer,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.delegate_decision(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.refresh_responsibility_notifications(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION goliath_api.admin_set_data_class_override(text,text,text,boolean,boolean,text) TO authenticated;
