import { GoliathError } from '../core/errors.js';
import type { EnterpriseProjectEvent } from '../events/types.js';
import { signWebhook, type ProviderIdentity, type ProviderWebhookAdapter, type RuntimeProvider, type RuntimeRouteRecord } from './provider-runtime.js';
import { timingSafeEqual } from 'node:crypto';

function integrationHeader(headers:Readonly<Record<string,string>>,suffix:string):string|undefined{
  // Keep the old EDAPOS webhook header namespace as an inbound-only migration alias.
  return headers[`x-goliath-${suffix}`]??headers[`x-edapos-${suffix}`];
}

function rec(v:unknown,label='payload'):Record<string,any>{if(!v||typeof v!=='object'||Array.isArray(v))throw new GoliathError('INVALID_INPUT',`${label} must be an object.`);return v as Record<string,any>}
function str(v:unknown,label:string):string{if(typeof v!=='string'||!v.trim())throw new GoliathError('INVALID_INPUT',`${label} is required.`);return v}
function iso(v:unknown,label:string):string{const s=str(v,label);if(!Number.isFinite(Date.parse(s)))throw new GoliathError('INVALID_INPUT',`${label} must be a valid date/time.`);return s}
function verify(secret:string,headers:Readonly<Record<string,string>>,raw:string):boolean{const got=integrationHeader(headers,'signature')??'';const exp=signWebhook(secret,raw);const a=Buffer.from(got);const b=Buffer.from(exp);return a.length===b.length&&timingSafeEqual(a,b)}
abstract class Signed implements ProviderWebhookAdapter { abstract readonly provider:RuntimeProvider; verify(secret:string,h:Readonly<Record<string,string>>,raw:string){return verify(secret,h,raw)} abstract identity(p:unknown,h:Readonly<Record<string,string>>,r:string):ProviderIdentity; abstract normalize(route:RuntimeRouteRecord,id:ProviderIdentity,p:unknown,r:string,c:string):EnterpriseProjectEvent; }

export class GitHubWebhookAdapter extends Signed {readonly provider='github' as const;identity(payload:unknown,h:Readonly<Record<string,string>>,receivedAt:string):ProviderIdentity{const p=rec(payload),pr=rec(p.pull_request,'pull_request');return{eventId:str(integrationHeader(h,'event-id')??p.deliveryId,'event id'),accountId:str(integrationHeader(h,'account-id'),'x-goliath-account-id'),resourceType:'pull-request',externalId:String(pr.number??str(p.number,'pull request number')),sourceVersion:String(pr.updated_at??receivedAt),sourceEffectiveAt:iso(pr.updated_at??receivedAt,'updated_at')}}normalize(route:RuntimeRouteRecord,id:ProviderIdentity,payload:unknown,receivedAt:string,correlationId:string):EnterpriseProjectEvent{const p=rec(payload),pr=rec(p.pull_request,'pull_request');const merged=pr.merged===true;const mergedAt=merged?iso(pr.merged_at,'merged_at'):undefined;return{kind:'activity.changed',projectId:route.projectId,organisationId:route.organisationId,entityId:route.localEntityId,sourceSystem:'GitHub',sourceTenant:id.accountId,sourceEventId:id.eventId,sourceRef:`GITHUB:${id.externalId}`,sourceRevision:id.sourceVersion,sourceEffectiveAt:id.sourceEffectiveAt,observedAt:receivedAt,correlationId,payload:{status:merged?'done':'in-progress',...(mergedAt?{actualFinish:mergedAt.slice(0,10),percentComplete:100}:{}),evidenceRefs:[`GITHUB:${id.externalId}:${id.eventId}`]}}}}
export class CiCdWebhookAdapter extends Signed {readonly provider='cicd' as const;identity(payload:unknown,h:Readonly<Record<string,string>>,receivedAt:string):ProviderIdentity{const p=rec(payload);return{eventId:str(p.eventId,'eventId'),accountId:str(integrationHeader(h,'account-id'),'x-goliath-account-id'),resourceType:'deployment',externalId:str(p.deploymentId,'deploymentId'),sourceVersion:String(p.revision??p.updatedAt??receivedAt),sourceEffectiveAt:iso(p.updatedAt??receivedAt,'updatedAt')}}normalize(route:RuntimeRouteRecord,id:ProviderIdentity,payload:unknown,receivedAt:string,correlationId:string):EnterpriseProjectEvent{const p=rec(payload);const state=str(p.state,'state').toLowerCase();const done=['success','succeeded','completed'].includes(state);const failed=['failed','error'].includes(state);const completedAt=done?iso(p.completedAt,'completedAt'):undefined;return{kind:'activity.changed',projectId:route.projectId,organisationId:route.organisationId,entityId:route.localEntityId,sourceSystem:'CI/CD',sourceTenant:id.accountId,sourceEventId:id.eventId,sourceRef:`CICD:${id.externalId}`,sourceRevision:id.sourceVersion,sourceEffectiveAt:id.sourceEffectiveAt,observedAt:receivedAt,correlationId,payload:{status:done?'done':failed?'blocked':'in-progress',...(done&&completedAt?{actualFinish:completedAt.slice(0,10),percentComplete:100}:{}),...(failed?{blocker:String(p.failureReason??'CI/CD deployment failed.')}:{blocker:null}),evidenceRefs:[`CICD:${id.externalId}:${id.eventId}`]}}}}
export class HrCapacityWebhookAdapter extends Signed {readonly provider='hr' as const;identity(payload:unknown,h:Readonly<Record<string,string>>,receivedAt:string):ProviderIdentity{const p=rec(payload);return{eventId:str(p.eventId,'eventId'),accountId:str(integrationHeader(h,'account-id'),'x-goliath-account-id'),resourceType:'capacity',externalId:str(p.resourceId,'resourceId'),sourceVersion:String(p.revision??1),sourceEffectiveAt:iso(p.updatedAt??receivedAt,'updatedAt')}}normalize(route:RuntimeRouteRecord,id:ProviderIdentity,payload:unknown,receivedAt:string,correlationId:string):EnterpriseProjectEvent{const p=rec(payload);return{kind:'resource.capacity.changed',projectId:route.projectId,organisationId:route.organisationId,entityId:id.externalId,sourceSystem:'HR',sourceTenant:id.accountId,sourceEventId:id.eventId,sourceRef:`HR:CAPACITY:${id.externalId}`,sourceRevision:id.sourceVersion,sourceEffectiveAt:id.sourceEffectiveAt,observedAt:receivedAt,correlationId,payload:{periodStart:str(p.periodStart,'periodStart'),periodEnd:str(p.periodEnd,'periodEnd'),grossHours:Number(p.grossHours),unavailableHours:Number(p.leaveHours??p.unavailableHours??0)}}}}
export class ProcurementWebhookAdapter extends Signed {readonly provider='procurement' as const;identity(payload:unknown,h:Readonly<Record<string,string>>,receivedAt:string):ProviderIdentity{const p=rec(payload);return{eventId:str(p.eventId,'eventId'),accountId:str(integrationHeader(h,'account-id'),'x-goliath-account-id'),resourceType:'finance-entry',externalId:str(p.purchaseOrderId,'purchaseOrderId'),sourceVersion:String(p.revision??1),sourceEffectiveAt:iso(p.updatedAt??receivedAt,'updatedAt')}}normalize(route:RuntimeRouteRecord,id:ProviderIdentity,payload:unknown,receivedAt:string,correlationId:string):EnterpriseProjectEvent{const p=rec(payload);if(typeof p.committedAmount!=='number'||p.committedAmount<0)throw new GoliathError('INVALID_INPUT','committedAmount must be a non-negative number.');return{kind:'finance.entry.changed',projectId:route.projectId,organisationId:route.organisationId,entityId:id.externalId,sourceSystem:'Procurement',sourceTenant:id.accountId,sourceEventId:id.eventId,sourceRef:`PROCUREMENT:${id.externalId}`,sourceRevision:id.sourceVersion,sourceEffectiveAt:id.sourceEffectiveAt,observedAt:receivedAt,correlationId,payload:{entryType:'commitment',amount:p.committedAmount,currency:str(p.currency,'currency'),occurredAt:id.sourceEffectiveAt,classification:'confidential'}}}}
export class TimesheetWebhookAdapter extends Signed {readonly provider='timesheet' as const;identity(payload:unknown,h:Readonly<Record<string,string>>,receivedAt:string):ProviderIdentity{const p=rec(payload);return{eventId:str(p.eventId,'eventId'),accountId:str(integrationHeader(h,'account-id'),'x-goliath-account-id'),resourceType:'worklog',externalId:str(p.worklogId,'worklogId'),sourceVersion:String(p.revision??1),sourceEffectiveAt:iso(p.updatedAt??receivedAt,'updatedAt')}}normalize(route:RuntimeRouteRecord,id:ProviderIdentity,payload:unknown,receivedAt:string,correlationId:string):EnterpriseProjectEvent{const p=rec(payload);return{kind:'resource.worklog.changed',projectId:route.projectId,organisationId:route.organisationId,entityId:id.externalId,sourceSystem:'Timesheet',sourceTenant:id.accountId,sourceEventId:id.eventId,sourceRef:`TIMESHEET:${id.externalId}`,sourceRevision:id.sourceVersion,sourceEffectiveAt:id.sourceEffectiveAt,observedAt:receivedAt,correlationId,payload:{resourceId:str(p.resourceId,'resourceId'),...(typeof p.activityId==='string'?{activityId:p.activityId}:{}),workDate:str(p.workDate,'workDate'),hours:Number(p.hours),billable:p.billable===true}}}}
export class M365TranscriptWebhookAdapter extends Signed {readonly provider='m365' as const;identity(payload:unknown,h:Readonly<Record<string,string>>,receivedAt:string):ProviderIdentity{const p=rec(payload);return{eventId:str(p.eventId,'eventId'),accountId:str(integrationHeader(h,'account-id'),'x-goliath-account-id'),resourceType:'transcript',externalId:str(p.meetingId,'meetingId'),sourceVersion:String(p.revision??1),sourceEffectiveAt:iso(p.completedAt??receivedAt,'completedAt')}}normalize(route:RuntimeRouteRecord,id:ProviderIdentity,payload:unknown,receivedAt:string,correlationId:string):EnterpriseProjectEvent{const p=rec(payload);return{kind:'meeting.transcript.received',projectId:route.projectId,organisationId:route.organisationId,entityId:id.externalId,sourceSystem:'M365',sourceTenant:id.accountId,sourceEventId:id.eventId,sourceRef:`M365:MEETING:${id.externalId}`,sourceRevision:id.sourceVersion,sourceEffectiveAt:id.sourceEffectiveAt,observedAt:receivedAt,correlationId,payload:{transcriptRef:str(p.transcriptRef,'transcriptRef'),text:str(p.text,'text'),...(typeof p.title==='string'?{meetingTitle:p.title}:{})}}}}
