import { createClient } from 'https://esm.sh/@neondatabase/neon-js@0.7.0-beta';
const DB='https://ep-twilight-unit-au4iuyze.c-10.us-east-1.aws.neon.tech/edapos';
const client=createClient(DB);
const app=document.getElementById('app');
let session=null, account=null, contexts=[], workspace=null, current='attention';
const labels={attention:'Attention',projects:'Projects',work:'Work',people:'People & capacity',money:'Money',admin:'Administration'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function rpc(name,payload={}){const {data,error}=await client.rpc(name,payload);if(error)throw new Error(error.message||String(error));return data;}
async function getSession(){const r=await client.auth.getSession();if(r.error)throw new Error(r.error.message);return r.data;}
function loginView(message=''){app.innerHTML=`<div class="login"><div class="login-card"><div class="login-brand"><img src="/goliath-head.png" alt="Goliath"><div><b>Goliath</b><div class="muted">Project Management Tracker</div></div></div><h1>Sign in to your project context</h1><p class="muted">Your identity determines which organisation, projects and responsibility contexts are available. You cannot choose arbitrary production roles.</p>${message?`<div class="error">${esc(message)}</div>`:''}<div class="actions"><button id="google" class="btn">Continue with Google</button></div><div class="notice"><strong>Migration note:</strong> the old role/persona selector remains a controlled acceptance tool only. Named-user access is now the production direction.</div></div></div>`;document.getElementById('google').onclick=async()=>{try{await client.auth.signIn.social({provider:'google',callbackURL:location.origin+'/'});}catch(e){loginView(e.message);}};}
async function loadIdentity(){account=await rpc('account_status');if(!account?.linked){const boot=await rpc('claim_bootstrap_identity').catch(()=>null);if(boot?.claimed)account=await rpc('account_status');} if(!account?.linked){unlinkedView();return;}contexts=await rpc('my_contexts');if(!Array.isArray(contexts)||!contexts.length){noContextsView();return;}workspace=await rpc('my_workspace',{p_assignment_id:contexts[0].assignment_id});appView();}
function unlinkedView(){app.innerHTML=`<div class="login"><div class="login-card"><div class="login-brand"><img src="/goliath-head.png" alt="Goliath"><div><b>Goliath</b><div class="muted">Authenticated account</div></div></div><h1>Account verified, access not linked</h1><p class="muted">Signed in as ${esc(account?.email||'authenticated user')}. Project access is granted only through an explicit Goliath identity invitation.</p><div class="notice">Ask your Enterprise Admin for the invitation token issued to this verified email. Email/domain alone does not grant project access.</div><label for="token"><b>Invitation token</b></label><input id="token" style="width:100%;padding:10px;margin-top:7px;border:1px solid #ddd;border-radius:8px" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"><div class="actions"><button id="claim" class="btn">Claim invitation</button><button id="signout" class="btn secondary">Sign out</button></div><div id="claimMsg"></div></div></div>`;document.getElementById('claim').onclick=async()=>{const msg=document.getElementById('claimMsg');try{const token=document.getElementById('token').value.trim();if(!token)throw new Error('Enter the invitation token.');await rpc('claim_identity_invitation',{p_token:token});await loadIdentity();}catch(e){msg.className='error';msg.textContent=e.message;}};document.getElementById('signout').onclick=signOut;}
function noContextsView(){app.innerHTML=`<div class="login"><div class="login-card"><h1>No active responsibility contexts</h1><p class="muted">Your account is linked, but there is currently no active Goliath responsibility assignment for ${esc(account?.email||'this account')}.</p><div class="actions"><button id="signout" class="btn secondary">Sign out</button></div></div></div>`;document.getElementById('signout').onclick=signOut;}
async function signOut(){await client.auth.signOut();session=null;account=null;contexts=[];workspace=null;loginView();}
function roleViews(role){if(role==='enterprise-admin')return ['admin','projects'];if(role==='resource-manager')return ['people','projects','money'];if(role==='portfolio-manager')return ['attention','projects','money'];if(role==='sponsor')return ['attention','projects','work','money'];if(role==='team-member'||role==='delivery-lead'||role==='agile-delivery-lead')return ['attention','work','projects'];return ['attention','projects','work','people','money'];}
function appView(){const views=roleViews(workspace.role);if(!views.includes(current))current=views[0];app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><img src="/goliath-head.png" alt="Goliath"><div><b>Goliath</b><span>Project Management Tracker</span></div></div><nav class="nav" id="nav"></nav></aside><main class="main"><header class="top"><div><b>Goliath Control</b><div class="top-user">${esc(account?.email||workspace.displayName)}</div></div><div class="context"><span class="muted">Responsibility</span><select id="contextSelect"></select><button id="signout" class="btn secondary">Sign out</button></div></header><div class="content"><div id="view"></div></div></main></div>`;renderNav();const sel=document.getElementById('contextSelect');sel.innerHTML=contexts.map(c=>`<option value="${esc(c.assignment_id)}" ${c.assignment_id===workspace.assignmentId?'selected':''}>${esc(c.display_name)} · ${esc(c.role)} · ${esc(c.scope_label||c.scope_id)}</option>`).join('');sel.onchange=async()=>{try{workspace=await rpc('my_workspace',{p_assignment_id:sel.value});appView();}catch(e){alert(e.message);}};document.getElementById('signout').onclick=signOut;render();}
function renderNav(){const views=roleViews(workspace.role);document.getElementById('nav').innerHTML=views.map(v=>`<button data-view="${v}" class="${v===current?'active':''}">${labels[v]}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{current=b.dataset.view;renderNav();render();});}
function kpi(label,value){return `<div class="card"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;}
function badge(v){const s=String(v||'').toLowerCase();const cls=s==='blocked'||s==='critical'?'bad':(s==='in-progress'||s==='active'||s==='done'?'good':'warn');return `<span class="badge ${cls}">${esc(v||'—')}</span>`;}
function projectTable(){const rows=(workspace.projects||[]).map(p=>`<tr><td><b>${esc(p.name)}</b><div class="muted">${esc(p.code)} · ${esc(p.lifecycle)}</div></td><td>${esc(p.blockedActivities)}</td><td>${esc(p.overdueActivities)}</td><td>${esc(p.forecastFinish||'—')}</td><td>${p.budget==null?'—':esc((p.currency||'')+' '+Number(p.budget).toLocaleString())}</td></tr>`).join('');return `<div class="panel"><table><thead><tr><th>Project</th><th>Blocked</th><th>Overdue</th><th>Forecast</th><th>Budget</th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="empty">No projects available.</td></tr>'}</tbody></table></div>`;}
function workTable(){const rows=(workspace.work||[]).map(w=>`<tr><td><b>${esc(w.title)}</b><div class="muted">${esc(w.projectId)} · ${esc(w.phase)}</div></td><td>${badge(w.status)}</td><td>${esc(w.ownerId||'Unassigned')}</td><td>${esc(w.teamId||'—')}</td><td>${esc(w.forecastFinish||w.baselineFinish||'—')}</td><td>${esc(w.percentComplete??0)}%</td></tr>`).join('');return `<div class="panel"><table><thead><tr><th>Work</th><th>Status</th><th>Owner</th><th>Team</th><th>Forecast</th><th>Progress</th></tr></thead><tbody>${rows||'<tr><td colspan="6" class="empty">No work items visible for this responsibility.</td></tr>'}</tbody></table></div>`;}
function attention(){const w=workspace.work||[],blocked=w.filter(x=>x.status==='blocked'),critical=w.filter(x=>x.priority==='critical');return `<h1>Attention</h1><p class="sub">Exceptions visible to the signed-in responsibility context.</p><div class="hero"><div><b>${esc(workspace.profile?.title)}</b><div class="muted">${esc(workspace.profile?.purpose)}</div></div><div class="chips"><span class="chip">${esc(workspace.scope?.type)}: ${esc(workspace.scope?.id)}</span><span class="chip">${esc(workspace.displayName)}</span></div></div><div class="grid">${kpi('Visible projects',(workspace.projects||[]).length)}${kpi('Visible work',w.length)}${kpi('Blocked',blocked.length)}${kpi('Critical',critical.length)}</div><div class="panel"><h3>Needs attention</h3>${blocked.concat(critical.filter(x=>!blocked.includes(x))).slice(0,10).map(x=>`<div style="padding:10px 0;border-top:1px solid #eee"><b>${esc(x.title)}</b><div class="muted">${esc(x.projectId)} · ${esc(x.blocker||x.priority||'')}</div></div>`).join('')||'<div class="empty">No material exceptions visible.</div>'}</div>`;}
function projects(){return `<h1>Projects</h1><p class="sub">Projects resolved server-side from this responsibility.</p><div class="grid">${kpi('Projects',(workspace.projects||[]).length)}${kpi('Blocked',(workspace.projects||[]).reduce((n,p)=>n+(p.blockedActivities||0),0))}${kpi('Overdue',(workspace.projects||[]).reduce((n,p)=>n+(p.overdueActivities||0),0))}${kpi('Unowned',(workspace.projects||[]).reduce((n,p)=>n+(p.unownedActivities||0),0))}</div>${projectTable()}`;}
function work(){return `<h1>Work</h1><p class="sub">The API omits work outside this responsibility scope.</p><div class="grid">${kpi('Visible items',(workspace.work||[]).length)}${kpi('In progress',(workspace.work||[]).filter(x=>x.status==='in-progress').length)}${kpi('Blocked',(workspace.work||[]).filter(x=>x.status==='blocked').length)}${kpi('Milestones',(workspace.work||[]).filter(x=>x.milestone==1||x.milestone===true).length)}</div>${workTable()}`;}
function people(){if(workspace.role==='resource-manager'){const c=workspace.capacity||{resources:[],demands:[]};return `<h1>People & capacity</h1><p class="sub">Functional capacity and demand for this Resource Manager scope.</p><div class="grid">${kpi('Resources',c.resources.length)}${kpi('Open demands',c.demands.filter(d=>d.state==='open').length)}${kpi('Required hours',c.demands.reduce((n,d)=>n+Number(d.requiredHours||0),0))}${kpi('Scope',workspace.scope?.id||'—')}</div>`;}return `<h1>People & capacity</h1><p class="sub">Project people visibility follows governed responsibility scope.</p>${projectTable()}`;}
function money(){const f=workspace.finance||[];return `<h1>Money</h1><p class="sub">Project financial projection visible to this responsibility.</p><div class="grid">${kpi('Budget',f.reduce((n,x)=>n+Number(x.budget||0),0).toLocaleString())}${kpi('EAC',f.reduce((n,x)=>n+Number(x.eac||0),0).toLocaleString())}${kpi('ETC',f.reduce((n,x)=>n+Number(x.etcAmount||0),0).toLocaleString())}${kpi('Projects',f.length)}</div>${projectTable()}`;}
function admin(){const a=workspace.administration;if(!a)return `<h1>Administration</h1><div class="error">Enterprise Admin responsibility is required.</div>`;const rows=(a.users||[]).map(u=>`<tr><td><b>${esc(u.displayName)}</b><div class="muted">${esc(u.userId)}</div></td><td>${esc((u.roles||[]).join(', '))}</td><td>${esc((u.teams||[]).filter(Boolean).join(', ')||'—')}</td></tr>`).join('');return `<h1>Administration</h1><p class="sub">Governed organisation directory. Identity invitations are issued separately and audited.</p><div class="grid">${kpi('Known users',a.knownUsers)}${kpi('Responsibility contexts',a.responsibilityContexts)}${kpi('Projects',(workspace.projects||[]).length)}${kpi('Identity','Named user')}</div><div class="panel"><table><thead><tr><th>User</th><th>Roles</th><th>Teams</th></tr></thead><tbody>${rows}</tbody></table></div>`;}
function render(){const body=current==='attention'?attention():current==='projects'?projects():current==='work'?work():current==='people'?people():current==='money'?money():admin();document.getElementById('view').innerHTML=body;}
(async()=>{try{const data=await getSession();session=data?.session||null;if(!session){loginView();return;}await loadIdentity();}catch(e){loginView(e.message);}})();
