import { createClient } from 'https://esm.sh/@neondatabase/neon-js@0.7.0-beta';
import { runtimeConfig } from './runtime-config.js';

const client=createClient({auth:{url:runtimeConfig.authUrl,allowAnonymous:false},dataApi:{url:runtimeConfig.dataApiUrl}});
const governed=new Set(['requirements','raid','change']);
const surfaceLabels={requirements:'Requirements',raid:'RAID',change:'Change & Baseline'};
let activeSurface=null,projectId=null,home=null,model=null,actionContext=null;

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function arr(v){return Array.isArray(v)?v:[];}
function fmt(v){return v?String(v).slice(0,10):'—';}
function badge(v){const s=String(v||'unknown').toLowerCase();const cls=['blocked','critical','rejected','overdue','invalidated'].includes(s)?'bad':['accepted','approved','active','applied','resolved','baselined','confirmed','closed'].includes(s)?'good':'warn';return `<span class="badge ${cls}">${esc(v||'—')}</span>`;}
async function rpc(name,payload={}){const {data,error}=await client.rpc(name,payload);if(error)throw new Error(error.message||String(error));return data;}
function contextId(){return document.getElementById('contextSelect')?.value||null;}
function view(){return document.getElementById('view');}
function toast(message,type='ok'){document.getElementById('govToast')?.remove();const t=document.createElement('div');t.id='govToast';t.className=`toast ${type}`;t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.remove(),3600);}
function modal(title,body,onSave,label='Save'){document.getElementById('govModal')?.remove();const o=document.createElement('div');o.id='govModal';o.className='modal-overlay';o.innerHTML=`<div class="modal-card"><div class="modal-head"><h3>${esc(title)}</h3><button class="icon-btn" data-close>×</button></div><div>${body}</div><div class="modal-actions"><button class="btn secondary" data-close>Cancel</button><button class="btn" data-save>${esc(label)}</button></div><div data-msg></div></div>`;document.body.appendChild(o);o.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>o.remove());o.querySelector('[data-save]').onclick=async()=>{const b=o.querySelector('[data-save]'),m=o.querySelector('[data-msg]');b.disabled=true;try{await onSave(o);o.remove();await load(activeSurface,projectId);toast('Saved.');}catch(e){m.className='error';m.textContent=e.message;}finally{b.disabled=false;}};return o;}
function coverage(c){const keys=['commitment','design','estimate','work','test','passedTest','acceptance'];const yes=keys.filter(k=>c?.[k]).length;return `${yes}/${keys.length}`;}
function projectSelector(){return `<div class="context" style="margin-bottom:14px"><select id="govProject">${arr(home?.projects).map(p=>`<option value="${esc(p.id)}" ${p.id===projectId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div>`;}
function markNav(surface){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.surface===surface));}
async function load(surface,pid=null){const ctx=contextId();if(!ctx)return;activeSurface=surface;home=await rpc('control_home',{p_assignment_id:ctx});const projects=arr(home.projects);projectId=pid&&projects.some(p=>p.id===pid)?pid:(projectId&&projects.some(p=>p.id===projectId)?projectId:projects[0]?.id||null);if(!projectId){render(`<h1>${esc(surfaceLabels[surface])}</h1><div class="panel empty">No governed project is available in this responsibility.</div>`);return;}[model,actionContext]=await Promise.all([rpc('project_control_extensions',{p_assignment_id:ctx,p_project_id:projectId}),rpc('project_action_context',{p_assignment_id:ctx,p_project_id:projectId}).catch(()=>({members:[],commitments:[]}))]);markNav(surface);renderSurface();}
function render(html){if(view())view().innerHTML=html;}
function bindProject(){const s=document.getElementById('govProject');if(s)s.onchange=()=>load(activeSurface,s.value);}

function requirementRows(){const reqs=arr(model?.requirements?.requirements);return reqs.map(r=>`<tr><td><b>${esc(r.title)}</b><div class="muted">${esc(r.requirementId)}</div></td><td>${badge(r.state)}</td><td>${esc(r.priority)}</td><td>${esc(r.ownerId||'—')}</td><td>${esc(r.source?.system||'—')}<div class="muted">${esc(r.source?.ref||'')} · ${esc(r.source?.version||'')}</div></td><td>${coverage(r.coverage)}</td><td>${r.proposedLinkCount||0}</td><td>${r.state==='proposed'?`<button class="mini" onclick="govBaselineRequirement('${esc(r.requirementId)}')">Baseline</button>`:''} <button class="mini secondary" onclick="govLinkRequirement('${esc(r.requirementId)}')">Link</button> ${['baselined','in-build','in-test'].includes(r.state)?`<button class="mini secondary" onclick="govAcceptRequirement('${esc(r.requirementId)}')">Accept</button>`:''}</td></tr>`).join('');}
function requirementsView(){const reqs=arr(model?.requirements?.requirements);return `${projectSelector()}<h1>Requirements</h1><p class="sub">Versioned requirements with computed traceability. Human-confirmed links count; AI proposals do not.</p><div class="grid"><div class="card"><span>Requirements</span><strong>${reqs.length}</strong></div><div class="card"><span>Unresolved proposed</span><strong>${reqs.filter(r=>r.state==='proposed').length}</strong></div><div class="card"><span>Accepted</span><strong>${reqs.filter(r=>r.state==='accepted').length}</strong></div><div class="card"><span>Manual RTM required</span><strong>No</strong></div></div><div class="actions"><button class="btn" onclick="govCreateRequirement()">New requirement</button></div><div class="panel table-wrap" style="margin-top:16px"><table><thead><tr><th>Requirement</th><th>State</th><th>Priority</th><th>Owner</th><th>Source</th><th>Coverage</th><th>Proposed links</th><th>Actions</th></tr></thead><tbody>${requirementRows()||'<tr><td colspan="8" class="empty">No governed requirements yet.</td></tr>'}</tbody></table></div>`;}

function raidView(){const items=arr(model?.raid?.items),triggers=arr(model?.raid?.triggerCandidates);return `${projectSelector()}<h1>RAID</h1><p class="sub">Live risks, issues and assumptions linked to commitments. Risk scoring is human-entered; deterministic triggers create issue candidates only.</p><div class="grid"><div class="card"><span>Risks</span><strong>${items.filter(x=>x.type==='risk').length}</strong></div><div class="card"><span>Issues</span><strong>${items.filter(x=>x.type==='issue').length}</strong></div><div class="card"><span>Assumptions</span><strong>${items.filter(x=>x.type==='assumption').length}</strong></div><div class="card"><span>Trigger candidates</span><strong>${triggers.length}</strong></div></div><div class="actions"><button class="btn" onclick="govCreateRaid()">New RAID item</button><button class="btn secondary" onclick="govEvaluateRaid()">Evaluate watched triggers</button></div><div class="panel table-wrap" style="margin-top:16px"><table><thead><tr><th>Type</th><th>Item</th><th>Owner</th><th>State</th><th>Exposure</th><th>Trigger</th><th>Commitments</th><th></th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.type)}</td><td><b>${esc(x.title)}</b><div class="muted">${esc(x.description)}</div></td><td>${esc(x.ownerId)}</td><td>${badge(x.state)}</td><td>${x.exposure??'—'}</td><td>${esc(x.triggerType||'—')} ${x.triggerRef?`<div class="muted">${esc(x.triggerRef)}</div>`:''}</td><td>${arr(x.commitments).length}</td><td><button class="mini secondary" onclick="govUpdateRaid('${esc(x.id)}','${esc(x.type)}','${esc(x.state)}',${x.likelihood??'null'},${x.impact??'null'})">Update</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No live RAID items.</td></tr>'}</tbody></table></div>${triggers.length?`<div class="panel"><h3>Issue candidates</h3>${triggers.map(t=>`<div class="timeline"><div><b>${esc(t.triggerType)} · ${esc(t.triggerRef||t.raidId)}</b><div class="muted">Observed ${fmt(t.observedAt)}. Human conversion required.</div></div><button class="mini" onclick="govConvertTrigger('${esc(t.id)}')">Convert to issue</button></div>`).join('')}</div>`:''}`;}

function changeRows(){return arr(model?.change?.changes).map(c=>`<tr><td><b>${esc(c.title)}</b><div class="muted">${esc(c.id)} · ${esc(c.sourceType)}</div></td><td>${badge(c.state)}</td><td>${esc(c.classification||'unclassified')}</td><td>${c.scheduleImpactDays??'—'}</td><td>${esc(c.impactCompleteness||'—')}</td><td>${c.approvalDecisionId?esc(c.approvalDecisionId):'—'}</td><td>${['draft','clarified'].includes(c.state)?`<button class="mini" onclick="govPrepareChange('${esc(c.id)}')">Prepare</button>`:''}${c.state==='pending-approval'?`<button class="mini secondary" onclick="govOpenDecisionQueue()">Decision queue</button> <button class="mini" onclick="govFinalizeChange('${esc(c.id)}')">Finalize</button>`:''}</td></tr>`).join('');}
function changeView(){const base=model?.baseline||{},current=base.current,pending=base.pendingApproval;return `${projectSelector()}<h1>Change & Baseline</h1><p class="sub">Approved baselines are immutable snapshots. Material change requires impact assessment, a named approval decision and a real baseline delta.</p><div class="grid"><div class="card"><span>Current baseline</span><strong>${current?`v${current.version}`:'None'}</strong></div><div class="card"><span>Approval pending</span><strong>${pending?'Yes':'No'}</strong></div><div class="card"><span>Change requests</span><strong>${arr(model?.change?.changes).length}</strong></div><div class="card"><span>Applied changes</span><strong>${arr(model?.change?.changes).filter(x=>x.state==='applied').length}</strong></div></div><div class="panel"><h3>Baseline</h3>${current?`<div><b>${esc(current.label||`Baseline v${current.version}`)}</b><div class="muted">Approved ${fmt(current.approvedAt)} by ${esc(current.approvedBy||'—')} · hash ${esc(String(current.hash||'').slice(0,12))}…</div></div>`:`<div class="notice">No approved project baseline exists yet.</div>`}${pending?`<div class="timeline"><div><b>Initial baseline approval pending</b><div class="muted">Decision ${esc(pending.decisionId)} · requested ${fmt(pending.requestedAt)}</div></div><span><button class="mini secondary" onclick="govOpenDecisionQueue()">Open decision queue</button> <button class="mini" onclick="govFinalizeBaseline()">Finalize after decision</button></span></div>`:''}<div class="actions">${!current&&!pending?`<button class="btn" onclick="govSubmitBaseline()">Submit initial baseline</button>`:''}<button class="btn secondary" onclick="govCreateChange()">New change request</button></div></div><div class="panel table-wrap"><h3>Change Desk</h3><table><thead><tr><th>Change</th><th>State</th><th>Classification</th><th>Schedule days</th><th>Impact</th><th>Decision</th><th>Actions</th></tr></thead><tbody>${changeRows()||'<tr><td colspan="7" class="empty">No change requests.</td></tr>'}</tbody></table></div>`;}

function renderSurface(){if(activeSurface==='requirements')render(requirementsView());else if(activeSurface==='raid')render(raidView());else if(activeSurface==='change')render(changeView());bindProject();}

async function createRequirement(){const members=arr(actionContext?.members);modal('Create governed requirement',`<div class="form-grid"><label class="span2">Title<input id="rTitle"></label><label>Master system<input id="rSystem" placeholder="goliath / CRM / CLM"></label><label>Source reference<input id="rRef"></label><label>Source version<input id="rVersion"></label><label>Priority<select id="rPriority"><option>medium</option><option>high</option><option>critical</option><option>low</option></select></label><label class="span2">Owner<select id="rOwner">${members.map(m=>`<option value="${esc(m.userId)}">${esc(m.displayName)} · ${esc(m.role)}</option>`).join('')}</select></label><label class="span2">Verbatim requirement<textarea id="rText" rows="4"></textarea></label></div>`,async o=>rpc('create_requirement',{p_assignment_id:contextId(),p_project_id:projectId,p_title:o.querySelector('#rTitle').value,p_master_system:o.querySelector('#rSystem').value,p_source_ref:o.querySelector('#rRef').value,p_source_version:o.querySelector('#rVersion').value,p_verbatim_text:o.querySelector('#rText').value,p_owner_id:o.querySelector('#rOwner').value,p_priority:o.querySelector('#rPriority').value}),'Create requirement');}
async function baselineRequirement(id){const reason=prompt('Why is this requirement ready to enter the governed baseline?');if(!reason)return;await rpc('baseline_requirement',{p_assignment_id:contextId(),p_requirement_id:id,p_reason:reason});await load(activeSurface,projectId);}
async function linkRequirement(id){const commitments=arr(actionContext?.commitments);if(!commitments.length){toast('No governed commitment is available to link.','error');return;}modal('Link requirement to commitment',`<label><b>Commitment</b><select id="rCommit" style="width:100%;padding:9px;margin-top:6px">${commitments.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('')}</select></label>`,async o=>rpc('link_requirement',{p_assignment_id:contextId(),p_requirement_id:id,p_link_type:'commitment',p_target_system:'goliath',p_target_type:'commitment',p_target_id:o.querySelector('#rCommit').value,p_target_version:null,p_origin:'human',p_confidence:'high'}),'Link');}
async function acceptRequirement(id){const refs=prompt('Acceptance evidence references, one per line:');if(!refs)return;const reason=prompt('Acceptance rationale:');if(!reason)return;await rpc('accept_requirement',{p_assignment_id:contextId(),p_requirement_id:id,p_evidence_refs:refs.split('\n').map(x=>x.trim()).filter(Boolean),p_reason:reason});await load(activeSurface,projectId);}

async function createRaid(){const members=arr(actionContext?.members),commitments=arr(actionContext?.commitments);const o=modal('Create RAID item',`<div class="form-grid"><label>Type<select id="xType"><option value="risk">Risk</option><option value="issue">Issue</option><option value="assumption">Assumption</option></select></label><label>Owner<select id="xOwner">${members.map(m=>`<option value="${esc(m.userId)}">${esc(m.displayName)}</option>`).join('')}</select></label><label class="span2">Title<input id="xTitle"></label><label class="span2">Description<textarea id="xDesc" rows="3"></textarea></label><label>Likelihood (risk only)<input id="xLike" type="number" min="1" max="5" value="3"></label><label>Impact (risk only)<input id="xImpact" type="number" min="1" max="5" value="3"></label><label>Validation date (assumption)<input id="xDate" type="date"></label><label>Linked commitment<select id="xCommit"><option value="">None</option>${commitments.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('')}</select></label><label class="span2">Response<input id="xResponse"></label></div>`,async m=>{const t=m.querySelector('#xType').value,cm=m.querySelector('#xCommit').value;await rpc('create_raid_item',{p_assignment_id:contextId(),p_project_id:projectId,p_item_type:t,p_title:m.querySelector('#xTitle').value,p_description:m.querySelector('#xDesc').value,p_owner_id:m.querySelector('#xOwner').value,p_likelihood_rating:t==='risk'?Number(m.querySelector('#xLike').value):null,p_impact_rating:t==='risk'?Number(m.querySelector('#xImpact').value):null,p_response:m.querySelector('#xResponse').value||null,p_trigger_type:t==='assumption'?'assumption-validation-date':null,p_trigger_ref:null,p_validation_date:t==='assumption'?m.querySelector('#xDate').value:null,p_commitment_ids:cm?[cm]:[]});},'Create');return o;}
async function evaluateRaid(){const r=await rpc('evaluate_raid_triggers',{p_assignment_id:contextId(),p_project_id:projectId});await load(activeSurface,projectId);toast(`${r.newIssueCandidates} new issue candidate(s).`);}
async function updateRaid(id,type,state,likelihood,impact){const reason=prompt('Update rationale:');if(!reason)return;const response=prompt('Current response / mitigation (optional):')||null;const next=prompt('New state (open, monitoring, responding, accepted, resolved, closed, invalidated):',state)||state;await rpc('update_raid_item',{p_assignment_id:contextId(),p_raid_id:id,p_state:next,p_response:response,p_likelihood_rating:type==='risk'?likelihood:null,p_impact_rating:type==='risk'?impact:null,p_reason:reason});await load(activeSurface,projectId);}
async function convertTrigger(id){const members=arr(actionContext?.members);modal('Convert trigger candidate to issue',`<div class="form-grid"><label>Issue owner<select id="tOwner">${members.map(m=>`<option value="${esc(m.userId)}">${esc(m.displayName)}</option>`).join('')}</select></label><label class="span2">Issue description<textarea id="tDesc" rows="3"></textarea></label><label class="span2">Conversion rationale<input id="tReason"></label></div>`,async o=>rpc('convert_raid_trigger_to_issue',{p_assignment_id:contextId(),p_trigger_event_id:id,p_owner_id:o.querySelector('#tOwner').value,p_description:o.querySelector('#tDesc').value,p_reason:o.querySelector('#tReason').value}),'Convert');}

async function submitBaseline(){const members=arr(actionContext?.members);modal('Submit initial baseline for approval',`<div class="form-grid"><label class="span2">Approver<select id="bApprover">${members.map(m=>`<option value="${esc(m.userId)}">${esc(m.displayName)} · ${esc(m.role)}</option>`).join('')}</select></label><label class="span2">Submission rationale<input id="bReason"></label></div><div class="notice">The approver must be a different named human. All in-scope commitments need owner, date, acceptance criteria and evidence specification, and proposed requirements must be resolved first.</div>`,async o=>rpc('submit_initial_baseline',{p_assignment_id:contextId(),p_project_id:projectId,p_approver_user_id:o.querySelector('#bApprover').value,p_reason:o.querySelector('#bReason').value}),'Submit');}
async function finalizeBaseline(){const reason=prompt('Baseline finalisation rationale:');if(!reason)return;try{await rpc('finalize_initial_baseline',{p_assignment_id:contextId(),p_project_id:projectId,p_reason:reason});await load(activeSurface,projectId);}catch(e){toast(e.message,'error');}}
async function createChange(){modal('Create change request',`<div class="form-grid"><label>Source<select id="cSource"><option value="manual">Manual</option><option value="client-request">Client request</option><option value="ticket">Ticket</option><option value="risk">Risk</option><option value="issue">Issue</option><option value="shadow-scope">Shadow scope</option><option value="other">Other</option></select></label><label>Source reference<input id="cRef"></label><label class="span2">Title<input id="cTitle"></label><label class="span2">Description<textarea id="cDesc" rows="3"></textarea></label></div>`,async o=>rpc('create_change_request',{p_assignment_id:contextId(),p_project_id:projectId,p_source_type:o.querySelector('#cSource').value,p_source_ref:o.querySelector('#cRef').value||null,p_title:o.querySelector('#cTitle').value,p_description:o.querySelector('#cDesc').value}),'Create change');}
async function prepareChange(id){const members=arr(actionContext?.members),commitments=arr(actionContext?.commitments);modal('Prepare change impact',`<div class="form-grid"><label>Classification<select id="cClass"><option value="material-change">Material change</option><option value="clarification">Clarification</option></select></label><label>Impact completeness<select id="cComplete"><option value="complete">Complete</option><option value="partial">Partial</option></select></label><label>Schedule impact days<input id="cDays" type="number" value="0"></label><label>Approver<select id="cApprover">${members.map(m=>`<option value="${esc(m.userId)}">${esc(m.displayName)} · ${esc(m.role)}</option>`).join('')}</select></label><label class="span2">Scope impact<input id="cScope"></label><label class="span2">Capacity impact<input id="cCapacity"></label><label class="span2">Risk impact<input id="cRisk"></label><label class="span2">Dependency impact<input id="cDependency"></label><label class="span2">Impacted commitment<select id="cCommit"><option value="">None</option>${commitments.map(c=>`<option value="${esc(c.id)}">${esc(c.title)}</option>`).join('')}</select></label><label>Proposed committed date<input id="cDate" type="date"></label><label class="span2">Proposed acceptance criteria<textarea id="cAcceptance" rows="3"></textarea></label><label class="span2">Impact note<input id="cNote"></label></div><div class="notice">The current MVP can apply committed-date and acceptance-criteria baseline deltas. Empty material changes cannot create a new baseline.</div>`,async o=>{const cm=o.querySelector('#cCommit').value;const delta=cm?[{commitmentId:cm,proposedCommittedDate:o.querySelector('#cDate').value||null,proposedAcceptanceCriteria:o.querySelector('#cAcceptance').value||null,impactNote:o.querySelector('#cNote').value||null}]:[];await rpc('prepare_change_request',{p_assignment_id:contextId(),p_change_request_id:id,p_classification:o.querySelector('#cClass').value,p_scope_impact:o.querySelector('#cScope').value||null,p_schedule_impact_days:Number(o.querySelector('#cDays').value||0),p_capacity_impact:o.querySelector('#cCapacity').value||null,p_cost_impact_amount:null,p_cost_impact_currency:null,p_risk_impact:o.querySelector('#cRisk').value||null,p_dependency_impact:o.querySelector('#cDependency').value||null,p_impact_completeness:o.querySelector('#cComplete').value,p_approver_user_id:o.querySelector('#cApprover').value,p_commitment_changes:delta});},'Submit impact');}
async function finalizeChange(id){const reason=prompt('Change finalisation rationale:');if(!reason)return;try{await rpc('finalize_change_request',{p_assignment_id:contextId(),p_change_request_id:id,p_reason:reason});await load(activeSurface,projectId);}catch(e){toast(e.message,'error');}}
function openDecisionQueue(){const b=document.querySelector('#nav button[data-surface="decisions"]');if(b)b.click();}

function attach(){document.querySelectorAll('#nav button').forEach(b=>{if(governed.has(b.dataset.surface))b.textContent=surfaceLabels[b.dataset.surface]||b.dataset.surface;});}
new MutationObserver(attach).observe(document.documentElement,{childList:true,subtree:true});attach();
document.addEventListener('click',e=>{const b=e.target.closest?.('#nav button[data-surface]');if(!b||!governed.has(b.dataset.surface))return;e.preventDefault();e.stopImmediatePropagation();load(b.dataset.surface).catch(err=>{render(`<div class="error">${esc(err.message)}</div>`);});},true);

Object.assign(window,{govCreateRequirement:createRequirement,govBaselineRequirement:baselineRequirement,govLinkRequirement:linkRequirement,govAcceptRequirement:acceptRequirement,govCreateRaid:createRaid,govEvaluateRaid:evaluateRaid,govUpdateRaid:updateRaid,govConvertTrigger:convertTrigger,govSubmitBaseline:submitBaseline,govFinalizeBaseline:finalizeBaseline,govCreateChange:createChange,govPrepareChange:prepareChange,govFinalizeChange:finalizeChange,govOpenDecisionQueue:openDecisionQueue});
